### PR TITLE
cleanup a lot and switch to jest for testing

### PR DESCRIPTION
**Pull request by samuelcolvin**
replaces #40.

cloudflare workers work really well with typescript, but the current typescript template has a lot wrong with it.

There are quite a lot of changes here, in rough order of priority:
* The complete work around for typescript checking `transpileOnly` is no longer enabled by default!
* `webpack.config.js` and `wrangler.toml` are fixed to work and not give warnings with wrangler
* `eslint` is added and configured with minimal defaults
* tests switch out mocha/chai for jest which is newer and generally easier and more powerful to use
* all packages are upgraded to latest versions
* `tsconfig.json` is cleaned up
* `package-lock.json` is removed

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Note: I got an error with webpack 5 and wrangler, which I didn't get with just raw `yarn build` I'm exactly sure what was causing it, but for this I've just used webpack 4.

**Comment by koeninger** [comment]
Thanks, why remove package-lock.json though?

**Comment by samuelcolvin** [comment]
* It's not necessary
* It confuses people
* It's specific to npm and many people use yarn

To reverse the question, why include it?

**Comment by koeninger** [comment]
Existing templates have it checked in, it allows for a consistent set of dependency versions, and npm is what we document as a recommended way to install wrangler.

**Comment by samuelcolvin** [comment]
Ok, no problem, feel free to add it.

**Comment by koeninger** [comment]
Will do, closing this in favor of https://github.com/cloudflare/worker-typescript-template/pull/42

Thanks again.

**Comment by samuelcolvin** [comment]
You know you can write to other people's PRs right?

No need to close this and create another.

**Comment by koeninger** [comment]
Don't want to bug you with any other minor changes that might come up, #42 is based off your branch so should still show up as contributor, thanks again for your help.

**Pull request closed without merging**
